tagsDict = {
    'abortion': '流產',
    'absorption': '吞噬吸收',
    'age progression': '快速成長',
    'age regression': '返老還童',
    'ahegao': '阿嘿顏',
    'alien': '外星人',
    'alien girl': '外星女孩',
    'all the way through': '頭尾貫通',
    'already uploaded': '曾經上傳過',
    'amputee': '截肢',
    'anal': '肛交',
    'anal birth': '肛門生育',
    'angel': '天使',
    'anorexic': '骨瘦如柴',
    'anthology': '選集',
    'apron': '圍裙',
    'armpit licking': '舔腋下',
    'armpit sex': '腋下交',
    'artbook': '畫集',
    'asphyxiation': '窒息',
    'assjob': '肛門摩擦',
    'aunt': '姑姑/阿姨',
    'autofellatio': '自己口交',
    'autopaizuri': '自己乳交',
    'bald': '禿頭',
    'ball sucking': '吸睪丸',
    'bandages': '繃帶',
    'bbm': '胖男',
    'bbw': '胖女',
    'bdsm': '施虐與受虐',
    'beauty mark': '美人痣',
    'bestiality': '獸交',
    'big areolae': '大乳暈',
    'big ass': '大屁股',
    'big balls': '大睪丸',
    'big breasts': '巨乳',
    'big clit': '大陰蒂',
    'big lips': '大嘴唇',
    'big nipples': '大乳頭',
    'big penis': '大陰莖',
    'big vagina': '大陰道',
    'bike shorts': '自行車短褲',
    'bikini': '比基尼',
    'birth': '出生',
    'bisexual': '雙性戀',
    'blackmail': '勒索',
    'blind': '盲人',
    'blindfold': '遮眼',
    'blood': '血',
    'bloomers': '運動短褲',
    'blowjob': '口交',
    'blowjob face': '口交臉',
    'body modification': '人體改造',
    'body painting': '人體彩繪',
    'bodystocking': '連身襪',
    'bodysuit': '緊身衣',
    'body swap': '靈魂交換',
    'body writing': '在身上寫字',
    'bondage': '綑綁',
    'brain fuck': '腦交',
    'breast expansion': '擴胸',
    'breast feeding': '餵乳',
    'bride': '新娘',
    'brother': '兄弟',
    'bukkake': '顏射',
    'bunny boy': '兔男孩',
    'bunny girl': '兔女郎',
    'business suit': '西裝/OL裝',
    'butler': '管家',
    'cannibalism': '食人',
    'cashier': '收銀員',
    'catboy': '貓男孩',
    'catfight': '貓鬥',
    'catgirl': '貓娘',
    'cbt': '虐待陰莖',
    'centaur': '半人馬',
    'cervix penetration': '子宮脫出',
    'chastity belt': '貞操帶',
    'cheating': '偷吃',
    'cheerleader': '啦啦隊員',
    'chikan': '痴漢',
    'chinese dress': '旗袍',
    'chloroform': '氯仿(迷藥)',
    'christmas': '聖誕節',
    'clamp': '夾子',
    'clit growth': '陰蒂增長',
    'clone': '複製',
    'closed eyes': '閉眼',
    'clothed female nude male': '女著衣男裸',
    'clothed male nude female': '男著衣女裸',
    'clothed paizuri': '著衣乳交',
    'coach': '教練',
    'collar': '項圈',
    'comic': '西方漫畫',
    'compilation': '合集',
    'condom': '保險套',
    'coprophagia': '食糞',
    'corruption': '墮落',
    'corset': '馬甲',
    'cosplaying': 'Cosplay',
    'cousin': '表兄弟姊妹',
    'cowgirl': '牛女',
    'crossdressing': '異性服裝',
    'crotch tattoo': '陰部刺青',
    'crown': '王冠',
    'cumflation': '精液脹腹',
    'cum swap': '精液交換',
    'cunnilingus': '舔陰',
    'cuntboy': '有穴的男孩',
    'dark nipples': '深色乳頭',
    'dark sclera': '深色鞏膜',
    'dark skin': '深色皮膚',
    'daughter': '女兒',
    'deepthroat': '深喉嚨',
    'defloration': '破處',
    'demon': '惡魔',
    'demon girl': '女惡魔',
    'diaper': '尿布',
    'dickgirl on dickgirl': '扶他X扶他',
    'dickgirl on male': '扶他X男人',
    'dickgirls only': '只有扶他',
    'dick growth': '陰莖增長',
    'dicknipples': '陰莖乳頭',
    'dilf': '熟男',
    'dog': '狗',
    'dog boy': '犬男',
    'dog girl': '犬娘',
    'doll joints': '可動人偶',
    'domination loss': '失去領導權',
    'double anal': '雙重肛交',
    'double blowjob': '雙重口交',
    'double penetration': '兩穴同時插入',
    'double vaginal': '雙重插入',
    'dougi': '武道服',
    'dragon': '龍',
    'drill hair': '雙螺旋髮型',
    'drugs': '毒品',
    'drunk': '喝醉',
    'ear fuck': '耳交',
    'eggs': '蛋',
    'electric shocks': '電擊',
    'elf': '精靈',
    'emotionless sex': '無感情性愛',
    'enema': '灌腸',
    'exhibitionism': '暴露狂',
    'eyemask': '眼部面罩',
    'eyepatch': '眼罩',
    'facesitting': '顏面騎乘',
    'facial hair': '鬍子',
    'fairy': '妖精',
    'farting': '放屁',
    'father': '父親',
    'females only': '只有女性',
    'femdom': '女性主導',
    'feminization': '女性化',
    'ffm threesome': '兩女一男',
    'fft threesome': '兩女一扶他',
    'filming': '錄影',
    'fingering': '指侵',
    'first person perspective': '第一人稱視角',
    'fishnets': '漁網襪',
    'fisting': '拳交',
    'focus anal': '肛交為主',
    'footjob': '足交',
    'foot licking': '舔足',
    'forbidden content': '禁止的內容',
    'forced exposure': '強迫暴露',
    'forniphilia': '人體家具',
    'fox boy': '狐狸男孩',
    'fox girl': '狐狸女郎',
    'freckles': '雀斑',
    'frottage': '陰莖摩擦(不只一人)',
    'full body tattoo': '全身紋身',
    'full censorship': '全色塊遮擋',
    'full color': '全彩',
    'fundoshi': '褌(兜檔布)',
    'furry': '獸人',
    'futanari': '扶他',
    'gag': '口球',
    'gaping': '撐開',
    'garter belt': '吊帶襪',
    'gender bender': '性別變化',
    'ghost': '鬼魂',
    'giant': '男巨人',
    'giantess': '女巨人',
    'gigantic breasts': '極巨乳',
    'glasses': '眼鏡',
    'glory hole': '尋歡洞',
    'gloves': '手套',
    'goblin': '哥布林',
    'gokkun': '飲精',
    'gothic lolita': '哥德蘿莉塔',
    'goudoushi': '合同誌',
    'grandmother': '祖母',
    'group': '群交',
    'growth': '體型增長',
    'guro': '獵奇',
    'gyaru': '辣妹',
    'gyaru-oh': '混混',
    'gymshorts': '運動短褲',
    'hair buns': '丸子頭',
    'hairjob': '髮交',
    'hairy': '多陰毛',
    'hairy armpits': '多腋毛',
    'handjob': '用手套弄陰莖',
    'harem': '後宮',
    'harness': '束縛',
    'harpy': '哈比',
    'heterochromia': '異色瞳',
    'hidden sex': '隱藏的性交',
    'horns': '角',
    'horse': '馬',
    'hotpants': '熱褲',
    'huge breasts': '超巨乳',
    'huge penis': '超巨屌',
    'human cattle': '人間牧場',
    'human on furry': '人與獸人',
    'human pet': '人寵',
    'humiliation': '凌辱',
    'impregnation': '使懷孕',
    'incest': '亂倫',
    'incomplete': '未完成',
    'infantilism': '返嬰癖',
    'inflation': '脹腹',
    'insect': '昆蟲',
    'insect girl': '昆蟲女',
    'inseki': '姻親',
    'inverted nipples': '凹陷乳頭',
    'invisible': '隱形',
    'josou seme': '女裝攻',
    'kemonomimi': '獸耳',
    'kimono': '和服',
    'kissing': '親吻',
    'kunoichi': '女忍者',
    'lab coat': '實驗服',
    'lactation': '母乳',
    'large insertions': '巨物插入',
    'large tattoo': '大面積刺青',
    'latex': '乳膠衣',
    'layer cake': '多穴輪插',
    'leash': '項圈',
    'leg lock': '夾腿',
    'leotard': '緊身連體衣',
    'lingerie': '內衣',
    'living clothes': '居家服',
    'lizard girl': '蜥蜴娘',
    'lolicon': '蘿莉',
    'long tongue': '長舌頭',
    'low bestiality': '少量獸交',
    'low lolicon': '少量蘿莉',
    'low scat': '少量排糞',
    'low shotacon': '少量正太',
    'machine': '機械',
    'magical girl': '魔法少女',
    'maid': '女僕',
    'makeup': '化妝',
    'male on dickgirl': '男人X扶他',
    'males only': '只有男性',
    'masked face': '面具',
    'masturbation': '手淫',
    'mecha girl': '機甲娘',
    'mermaid': '美人魚',
    'metal armor': '金屬盔甲',
    'midget': '侏儒',
    'miko': '巫女',
    'milf': '熟女',
    'military': '軍裝',
    'milking': '擠乳',
    'mind break': '精神崩潰',
    'mind control': '思想控制',
    'minigirl': '迷你女性',
    'miniguy': '迷你男性',
    'minotaur': '米諾陶',
    'missing cover': '封面缺失',
    'mmf threesome': '二男一女',
    'mmm threesome': '三男',
    'monster': '怪物',
    'monster girl': '怪物娘',
    'moral degeneration': '道德淪喪',
    'mosaic censorship': '馬賽克遮擋',
    'mother': '母親',
    'mouse girl': '鼠娘',
    'mouth mask': '口罩',
    'mtf threesome': '一男一女一扶他',
    'multiple breasts': '多個乳房',
    'multipul paizuri': '多人乳交',
    'multiple penises': '多根陰莖',
    'multi-work series': '多作品系列',
    'muscle': '肌肉',
    'nakadashi': '中出',
    'navel fuck': '肚臍交',
    'necrophilia': '姦屍',
    'netorare': 'NTR',
    'niece': '姪女',
    'nijisanji': '彩虹社',
    'ninja': '忍者',
    'nipple expansion': '乳頭膨脹',
    'nipple fuck': '乳頭交',
    'non-h': '無H',
    'no penetration': '無插入',
    'nose hook': '鼻鉤',
    'nudity only': '只有裸體(無性交)',
    'nun': '修女',
    'nurse': '護士',
    'octopus': '章魚',
    'oil': '抹油',
    'old man': '老人',
    'omorashi': '漏尿',
    'onahole': '自慰器',
    'oni': '日本鬼',
    'oppai loli': '巨乳蘿莉',
    'orc': '獸人',
    'orgasm denial': '高潮禁止',
    'out of order': '順序不一',
    'oyakodon': '母女丼',
    'paizuri': '乳交',
    'pantyhose': '連褲襪',
    'pantyjob': '摩擦內褲自慰',
    'parasite': '寄生',
    'pasties': '胸貼',
    'pegging': '男性被插入',
    'petplay': '調教',
    'phimosis': '包莖',
    'phone sex': '電愛',
    'piercing': '穿孔',
    'pig': '豬',
    'pig man': '豬男',
    'pillory': '頸手枷',
    'piss drinking': '飲尿',
    'pixie cut': '小精靈短髮',
    'plant girl': '植物娘',
    'policeman': '男警',
    'policewoman': '女警',
    'ponytail': '馬尾',
    'poor grammar': '語法錯誤',
    'possession': '肉體被佔據',
    'pregnant': '懷孕',
    'priest': '牧師',
    'prolapse': '脫肛',
    'prostate massage': '前列腺按摩',
    'prostitution': '賣淫',
    'pubic stubble': '部分陰毛',
    'public use': '公共使用',
    'raccoon girl': '浣熊娘',
    'randoseru': '小學生用書包',
    'rape': '強姦',
    'replaced': '被取代(已有新版)',
    'rimjob': '舔肛門',
    'robot': '機器人',
    'ryona': '女性受虐',
    'saliva': '唾液',
    'sample': '樣本',
    'scanmark': '掃描痕跡',
    'scar': '傷痕',
    'scat': '排糞',
    'schoolboy uniform': '男學生制服',
    'schoolgirl uniform': '女學生制服',
    'school swimsuit': '死庫水',
    'scrotal lingerie': '陰囊內衣',
    'selfcest': '自己X自己',
    'sex toys': '性玩具',
    'shared senses': '感官共享',
    'shaved head': '平頭',
    'sheep girl': '綿羊娘',
    'shemale': '女雄',
    'shibari': '繩縛',
    'shimaidon': '姊妹丼',
    'shimapan': '條紋內褲',
    'shotacon': '正太',
    'shrinking': '體型縮小',
    'sister': '姐姐/妹妹',
    'skinsuit': '人皮衣',
    'slave': '奴隸',
    'sleeping': '睡姦',
    'slime': '史萊姆',
    'slime girl': '史萊姆娘',
    'small breasts': '貧乳',
    'small penis': '小陰莖',
    'smegma': '包皮垢',
    'smell': '劇臭',
    'smoking': '性交時抽菸',
    'snake': '蛇',
    'snake girl': '蛇女',
    'snuff': '虐殺',
    'sole dickgirl': '只有一個扶他',
    'sole female': '只有一個女性',
    'sole male': '只有一個男性',
    'solo action': '自慰',
    'soushuuhen': '總集編',
    'spanking': '打屁股',
    'speculum': '窺器',
    'spider girl': '蜘蛛娘',
    'squid girl': '烏賊娘',
    'squirting': '潮吹',
    'stewardess': '女服務員',
    'stockings': '絲襪',
    'stomach deformation': '胃變形',
    'story arc': '故事情節',
    'strap-on': '假陰莖',
    'stretching': '擴張',
    'stuck in wall': '卡在牆中',
    'sumata': '股交',
    'sundress': '背心裙',
    'sunglasses': '太陽眼鏡',
    'sweating': '流汗',
    'swimsuit': '泳裝',
    'swinging': '交換伴侶',
    'syringe': '注射器',
    'table masturbation': '用桌子自慰',
    'tail': '尾巴',
    'tailjob': '尾交',
    'tail plug': '尾塞',
    'tall girl': '高的女性',
    'tall man': '高的男性',
    'tankoubon': '單行本',
    'tanlines': '曬痕',
    'teacher': '老師',
    'tentacles': '觸手',
    'thick eyebrows': '濃眉',
    'thigh high boots': '過膝靴',
    'tiara': '冕狀頭飾',
    'tickling': '搔癢',
    'tights': '緊身服',
    'time stop': '時間暫停',
    'tomboy': '男人婆',
    'tomgirl': '偽娘',
    'torture': '拷問',
    'tracksuit': '運動服',
    'trampling': '踩踏',
    'transformation': '身體變化',
    'tribadism': '女陰摩擦',
    'triple penetration': '三穴同時插入',
    'triple vaginal': '三重插入',
    'ttf threesome': '二扶他一女',
    'ttm threesome': '二扶他一男',
    'tube': '管子插入',
    'tutor': '家教',
    'twins': '雙胞胎',
    'twintails': '雙馬尾',
    'unbirth': '陰道吞噬',
    'uncensored': '無修',
    'uncle': '叔叔/伯伯',
    'underwater': '水中',
    'unusual pupils': '特殊瞳孔',
    'unusual teeth': '特殊牙齒',
    'urethra insertion': '尿道插入',
    'urination': '排尿',
    'vaginal sticker': '陰部貼紙',
    'vampire': '吸血鬼',
    'very long hair': '超長髮',
    'virginity': '處女',
    'vomit': '嘔吐',
    'vore': '捕食',
    'voyeurism': '偷窺',
    'waiter': '男服務生',
    'waitress': '女服務生',
    'watermarked': '有水印',
    'webtoon': '網頁漫畫',
    'weight gain': '體重增長',
    'western': '西方漫畫',
    'wet clothes': '濕身',
    'whip': '鞭打',
    'widow': '寡婦',
    'wings': '翅膀',
    'witch': '魔女(服裝)',
    'wolf': '狼',
    'wolf boy': '男狼人',
    'wolf girl': '女狼人',
    'wooden horse': '三角木馬',
    'worm': '蟲子',
    'wormhole': '蟲洞',
    'wrestling': '摔角',
    'x-ray': 'X光',
    'yandere': '病嬌',
    'yaoi': 'BL',
    'yuri': '百合',
    'zombie': '殭屍',
}
langDict = {
    'chinese': '中文',
    'japanese': '日文',
    'translated': '已翻譯',
    'english': '英文',
}
